# Generated by Django 5.2 on 2025-05-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_event_completion_date_event_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
