# Generated by Django 5.2 on 2025-05-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_event_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="duration",
            field=models.PositiveIntegerField(default=1, help_text="Duration in hours"),
        ),
    ]
