# Generated by Django 5.2 on 2025-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_event_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_participants",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
