# Generated by Django 5.2 on 2025-05-31 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_event_max_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="duration",
        ),
        migrations.AddField(
            model_name="event",
            name="duration_hours",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Duration of the event in hours",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
    ]
