# Generated by Django 5.2 on 2025-06-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_event_duration_event_duration_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerprofile",
            name="name",
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
