# Generated by Django 5.2 on 2025-06-01 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_volunteerprofile_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="rejected_requests",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
