# Generated by Django 5.2 on 2025-06-08 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_requeststatus_approved_at_alter_event_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfeedback",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
