# Generated by Django 5.2 on 2025-06-08 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_eventfeedback_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfeedback",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_feedbacks",
                to="core.event",
            ),
        ),
    ]
